language: node_js
node_js:
    - 0.8
language: ruby
rvm:
    - 2.0.0
before_install:
  - mkdir $TRAVIS_BUILD_DIR/travis-phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $TRAVIS_BUILD_DIR/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $TRAVIS_BUILD_DIR/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $TRAVIS_BUILD_DIR/travis-phantomjs
install:
    - ./bootstrap.sh --noprompt --directory ./narwhal
    - git clone https://github.com/cappuccino/cucapp.git
    - cd cucapp; jake install; cd ..
    - git clone https://github.com/cappuccino/OJTest.git
    - cd OJTest; jake install; cd ..
script:
    - jake test
    - jake cucumber-test
env: PATH="$TRAVIS_BUILD_DIR/narwhal/bin:$PATH" PATH=$TRAVIS_BUILD_DIR/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH CAPP_BUILD="$TRAVIS_BUILD_DIR/Build" NARWHAL_ENGINE=rhino BROWSER=phantomjs
